fresh/urls.py
from django.contrib import admin
from django.urls import include, path
from smorandev import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('smorandev.urls'))
]

handler404 = views.error_404

smoran-dev/smorandev/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.IndexView.as_view(), name='home'),
]

smorandev/smorandev/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

smorandev/urls.py
from django.urls import path

from . import views

app_name = 'smorandev'
urlpatterns = [
    path('', views.StaticView.as_view(), name='index'),
    path('projects/', views.ProjectList.as_view(), name='project-index'),
    path('resume/', views.pdf_view, name='resume'),
    path('projects/<str:slug>/', views.ProjectView.as_view(), name='project')
]

smorandev/models.py
from django.db import models
from django.utils.text import slugify


DEFAULT_LINK = "https://s3.us-east-2.amazonaws.com/smoran.dev/images/default.png"
class Project(models.Model):
    project_name = models.CharField(primary_key=True, verbose_name="Name", max_length=100)
    project_detail = models.TextField(verbose_name="Description", default="Description")
    github = models.URLField(verbose_name="Github Link", default=None, blank=True, null=True)
    blurb = models.TextField(verbose_name="Blurb", default="Sample text")
    technologies = models.TextField(default="Python, probably")
    markdown = models.BooleanField(default=False)
    image = models.TextField(verbose_name="Image Link", default=DEFAULT_LINK)
    image_size = models.TextField(default="col-md-4")
    webgl_path = models.TextField(default=None, blank=True, null=True)  # Path in static/ for projects that use WebGL
    webgl_vshader = models.TextField(verbose_name="Vertex Shader", default=None, blank=True, null=True)
    webgl_fshader = models.TextField(verbose_name="Fragment Shader", default=None, blank=True, null=True)
    slug = models.SlugField(default="")

    #Override save method to provide slugified version of PK
    def save(self, *args, **kwargs):
        self.slug = slugify(self.project_name)
        super(Project, self).save(*args, **kwargs)

    def __str__(self):
        return self.project_name

smorandev/views.py
from django.http import FileResponse, Http404
from django.shortcuts import render
from django.views import generic
from django.conf import settings
from django.templatetags.static import static
import random
import os


from .models import Project


# Home is now a list view, to add projects to cards on homepage
class StaticView(generic.ListView):
    template_name = 'smorandev/index.html'
    context_object_name = 'project_list'

    def get_queryset(self):
        # Choose some random projects to display links to from homepage
        projects = []
        for p in Project.objects.all():
            projects.append(p.pk)
        random.shuffle(projects)
        picks = projects[0:2]

        # Pass projects to template
        return Project.objects.filter(pk__in=picks)


class ProjectView(generic.DetailView):
    model = Project
    template_name = 'smorandev/project.html'


class ProjectList(generic.ListView):
    template_name = 'smorandev/project-index.html'
    context_object_name = 'project_list'

    def get_queryset(self):
        return Project.objects.all()


# Serves my resume as a PDF!
def pdf_view(request):
    try:
        url = os.path.join(settings.STATIC_ROOT, 'smoran_resume.pdf')
        return FileResponse(open(url, 'rb'), content_type='application/pdf')
    except FileNotFoundError:
        raise Http404()


def error_404(request, *args, **kwargs):
    data = {}
    return render(request, 'smorandev/404.html', data)

smorandev/templates/smorandev/base.html
{% load static %}

<!doctype html>
<html lang="en">
    <head>

        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        {# Bootstrap CSS! #}
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        {# style.css #}
        <link rel="stylesheet" type="text/css" href="{% static 'smorandev/style.css' %}">
    </head>

    <body class="d-flex flex-column">
        <div id="page-content">
            <div class="container">
                <div class="nav-container">
                    <h1><a href="{% url 'smorandev:index' %}" style="color:white; text-decoration: none;">smoran.dev</a></h1>
                        <ul class="nav justify-content-center">
                            <li class="nav-item">
                                <a class="nav-link active" href="{% url 'smorandev:index' %}">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'smorandev:project-index' %}">Projects</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'smorandev:resume' %}">Résumé</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="https://github.com/sdmoran">GitHub</a>
                            </li>
                        </ul>
                </div>
            </div>
        {% block content %}
        {% endblock %}
        </div>
            <footer class="footer navbar-fixed-bottom">
                <div class="container">
                    <div class="footer-container">
                        <p>smoran.dev</p>
                        <p> - </p>
                        <a href="mailto:smoran@wpi.edu">Contact</a>
                    </div>
                </div>
            </footer>
    </body>
</html>

smorandev/templates/smorandev/index.html
{% extends 'smorandev/base.html' %}

{% block content %}
    <br>
    <div class="container">
        <div class="jumbotron">
            <h1 class="display-4">Welcome!</h1>
        <p class="lead">This is the personal website of Sam Moran.</p>
            <hr>
        <p>
            I'm a Computer Science student at Worcester Polytechnic Institute. I created this website to learn web
        technologies as well as showcase some projects that I've worked on. Take a look around!
        </p>
        </div>
    </div>
    <div class="container">
        <div class="row">
            {% for project in project_list %}
            <div class="col-sm">
                <div class="card">
                    <img src="{{ project.image }}" class="card-img-top mx-auto" alt="Project image">
                    <div class="card-body">
                        <h5 class="card-title">{{ project.project_name }}</h5>
                        <p>{{ project.blurb }}</p>
                        <a href="{% url "smorandev:project" project.slug %}" class="btn btn-primary">Go to project!</a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

smorandev/templates/smorandev/project-index.html
{% extends 'smorandev/base.html' %}

{% block content %}
    <br>
    <div class="container">
        <div class="col sm" style="color: black;">
            <h1 style="text-align: left;">Projects</h1>
            <p>Here's a list of some of the projects that I've done! Each project has a list of some of the languages
                and technologies I used.</p>
        </div>
    {% if project_list %}
            <ul class="list-group">
            {% for project in project_list %}
            <li class="list-group-item">
                <div class="row">
                    <div class="col sm">
                        <h3><a href="{% url 'smorandev:project' project.slug %}">{{ project.project_name }}</a></h3>
                        <span>{{ project.blurb }}</span>
                        <br>
                        <span class="font-weight-light">{{ project.technologies }}</span>
                    </div>
                </div>
            </li>
            {% endfor %}
            </ul>
        </div>

    {% endif %}
{% endblock %}

smorandev/templates/smorandev/project.html
{% extends 'smorandev/base.html' %}
{% load static %}
{% load dat_files %}
{% load markdown_extras %}

{% block content %}
{{ project.project.technologies | markdown | safe}}
    <br>
    <div class="container">
        <div class="col sm" style="color: black;">
            <h1>{{ project.project_name }}</h1>
            {% if project.github %}
                <p><a href="{{ project.github }}">GitHub Repository</a></p>
            {% endif %}
            <p>
                {% if project.markdown %}
                {{ project.project_detail | markdown | safe}}
                {% else %}
                {{ project.project_detail | linebreaks }}
                {% endif %}
            </p>


            <h5>Technologies</h5>
            <p>{{ project.technologies }}</p>
            {% if project.webgl_path %}
                    <h5>WebGL</h5>
                    <div class="d-flex justify-content-center">
                        <script src="{% static 'smorandev/webgl/lib/webgl-utils.js' %}"></script>
                        <script src="{% static 'smorandev/webgl/lib/initShaders.js'%}"></script>
                        <script src="{% static 'smorandev/webgl/lib/MV.js'%}"></script>
        {#                Load vertex shader from the project object #}
                        <script id="vshader" type="x-shader/x-vertex">
                        {{ project.webgl_vshader }}
                        </script>
                        <script id="fshader" type="x-shader/x-fragment">
                        {{ project.webgl_fshader }}
                        </script>
                        <div id="webgl-container" class="text-center">
                            <canvas class="canvas" id="webgl" width="400" height="400" style="border:1px solid; background:white">
                                Please use a browser that supports the "canvas" tag.
                            </canvas>
                        </div>
                        <script src="{% static project.webgl_path %}"></script>
                        </div>
        {#              This is REALLY COOL! Gets list of dat files in directory for webgl project. #}
                        {% get_datfiles project.webgl_path as dat %}
                        {% if dat %}
                                <p class="text-center">Choose a premade file to display, or upload your own!</p>
                                <div class="d-flex justify-content-center" id="serverFiles">
                                    <select class="d-flex justify-content-center" onchange="loadFileFromServer(event, '{% static project.webgl_path %}')">
                                        {% for d in dat %}
                                            <option>{{ d }}</option>
                                        {% endfor %}
                                    </select>
                                </div>
                            <br>
                            <div id="fileContainer" class="d-flex justify-content-center"></div>
                        {% endif %}
                    {% else %}
                    <h5>Images</h5>
                    <div class="row">
                         <div class="{{ project.image_size }} mx-auto">
                            <div class="card">
                                <img src="{{ project.image }}" class="card-img-top mx-auto" alt="Project image">
                            </div>
                        </div>
                    </div>
                    {% endif %}
        </div>
    </div>
    <script>main()</script>
{% endblock %}

smorandev/templates/smorandev/webgl-project.html
{% extends 'smorandev/project.html' %}

{% block webgl %}
    <canvas class="canvas" id="webgl" width="400" height="400" style="border:1px solid; display: inline">
        Please use a browser that supports the "canvas" tag.
    </canvas>
{% endblock %}